# 📄 Multi-Document PDF RAG Assistant

**Tech Stack:** pypdf · sentence-transformers · FAISS · TinyLlama-1.1B-Chat

## 0. Runtime Check
Pastikan GPU aktif: **Runtime → Change runtime type → T4 GPU**

In [35]:
import torch
print(f'PyTorch version : {torch.__version__}')
print(f'CUDA available  : {torch.cuda.is_available()}')
if torch.cuda.is_available():
    print(f'GPU             : {torch.cuda.get_device_name(0)}')

PyTorch version : 2.10.0+cu128
CUDA available  : True
GPU             : Tesla T4

## 1. Install Dependencies

In [36]:
!pip install pypdf bitsandbytes faiss-cpu
print('✅ Dependencies installed')

Requirement already satisfied: pypdf in /usr/local/lib/python3.12/dist-packages (6.12.1)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.2)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.4.6)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3,>=2.3->bitsandbytes) (1.5.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
✅ Dependencies installed

## 2. Clone Repository & Setup Structure

In [ ]:
import os
import shutil
from kaggle_secrets import UserSecretsClient

user_secrets = UserSecretsClient()
github_token = user_secrets.get_secret("GITHUB_TOKEN")

github_username = "rakdaf08"
repo_name = "nolimit-ds-test-rakadaffa"

if os.path.exists(repo_name):
    shutil.rmtree(repo_name)
    print(f"Folder {repo_name} berhasil dihapus.")

!git clone https://{github_token}@github.com/{github_username}/{repo_name}.git

%cd {repo_name}

Cloning into 'nolimit-ds-test-rakadaffa'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 25 (delta 6), reused 23 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (25/25), 18.04 KiB | 3.01 MiB/s, done.
Resolving deltas: 100% (6/6), done.
/kaggle/working/nolimit-ds-test-rakadaffa/nolimit-ds-test-rakadaffa/nolimit-ds-test-rakadaffa

## 3. Dataset Exploration (Phase 1 Task 2)

In [40]:
import sys, json
sys.path.insert(0, 'src')
from loader import get_dataset_summary
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

summary = get_dataset_summary('/kaggle/input/datasets/manisha717/dataset-of-pdf-files/Pdf')
print(f"Total PDFs  : {summary['total_files']}")
print(f"Total pages : {summary['total_pages']}")
print()
df = pd.DataFrame(summary['files'])
display(df)

parsing for Object Streams
incorrect startxref pointer(1)
parsing for Object Streams
parsing for Object Streams
invalid pdf header: b'\r\n\r\n\r'
CAUTION: startxref found while searching for %%EOF. The file might be truncated and some data might not be read.
EOF marker not found
Ignoring wrong pointing object 1 65536 (offset 0)
Ignoring wrong pointing object 15 65536 (offset 0)
incorrect startxref pointer(3)
incorrect startxref pointer(3)
parsing for Object Streams
incorrect startxref pointer(3)
incorrect startxref pointer(4)
parsing for Object Streams
invalid pdf header: b'\n<!DO'
EOF marker not found
Ignoring wrong pointing object 2 65536 (offset 0)
Ignoring wrong pointing object 35 65536 (offset 0)
Ignoring wrong pointing object 55 65536 (offset 0)
Ignoring wrong pointing object 74 65536 (offset 0)
Ignoring wrong pointing object 92 65536 (offset 0)
Ignoring wrong pointing object 112 65536 (offset 0)
Ignoring wrong pointing object 139 65536 (offset 0)
Ignoring wrong pointing object 158 65536 (offset 0)
incorrect startxref pointer(3)
incorrect startxref pointer(3)
incorrect startxref pointer(3)
parsing for Object Streams
incorrect startxref pointer(3)
incorrect startxref pointer(3)
EOF marker not found
Ignoring wrong pointing object 2 65536 (offset 0)
Ignoring wrong pointing object 44 65536 (offset 0)
Ignoring wrong pointing object 72 65536 (offset 0)
Ignoring wrong pointing object 99 65536 (offset 0)
Ignoring wrong pointing object 125 65536 (offset 0)
Ignoring wrong pointing object 153 65536 (offset 0)
Ignoring wrong pointing object 190 65536 (offset 0)
Ignoring wrong pointing object 218 65536 (offset 0)
incorrect startxref pointer(3)
Ignoring padding error: Invalid padding bytes.
incorrect startxref pointer(3)
XRef object at 1266 can not be read, some object may be missing
Ignoring wrong pointing object 38 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 40 0 (offset 0)
Ignoring wrong pointing object 41 0 (offset 0)
Ignoring wrong pointing object 42 0 (offset 0)
Ignoring wrong pointing object 43 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)
Ignoring wrong pointing object 45 0 (offset 0)
Ignoring wrong pointing object 46 0 (offset 0)
Ignoring wrong pointing object 47 0 (offset 0)
Ignoring wrong pointing object 48 0 (offset 0)
Ignoring wrong pointing object 49 0 (offset 0)
Ignoring wrong pointing object 50 0 (offset 0)
Ignoring wrong pointing object 51 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 53 0 (offset 0)
Ignoring wrong pointing object 54 0 (offset 0)
Ignoring wrong pointing object 55 0 (offset 0)
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 57 0 (offset 0)
Ignoring wrong pointing object 58 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 60 0 (offset 0)
Ignoring wrong pointing object 61 0 (offset 0)
Ignoring wrong pointing object 62 0 (offset 0)
Ignoring wrong pointing object 63 0 (offset 0)
Ignoring wrong pointing object 64 0 (offset 0)
Ignoring wrong pointing object 65 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
Ignoring wrong pointing object 67 0 (offset 0)
Ignoring wrong pointing object 68 0 (offset 0)
Ignoring wrong pointing object 69 0 (offset 0)
Ignoring wrong pointing object 70 0 (offset 0)
Ignoring wrong pointing object 71 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 73 0 (offset 0)
Ignoring wrong pointing object 74 0 (offset 0)
Ignoring wrong pointing object 75 0 (offset 0)
Ignoring wrong pointing object 76 0 (offset 0)
Ignoring wrong pointing object 77 0 (offset 0)
Ignoring wrong pointing object 78 0 (offset 0)
Ignoring wrong pointing object 79 0 (offset 0)
Ignoring wrong pointing object 80 0 (offset 0)
Ignoring wrong pointing object 81 0 (offset 0)
Ignoring wrong pointing object 82 0 (offset 0)
Ignoring wrong pointing object 83 0 (offset 0)
Ignoring wrong pointing object 84 0 (offset 0)
Ignoring wrong pointing object 85 0 (offset 0)
Ignoring wrong pointing object 86 0 (offset 0)
Ignoring wrong pointing object 87 0 (offset 0)
Ignoring wrong pointing object 88 0 (offset 0)
Ignoring wrong pointing object 89 0 (offset 0)
Ignoring wrong pointing object 90 0 (offset 0)
Ignoring wrong pointing object 91 0 (offset 0)
Ignoring wrong pointing object 92 0 (offset 0)
Ignoring wrong pointing object 93 0 (offset 0)
Ignoring wrong pointing object 94 0 (offset 0)
Ignoring wrong pointing object 95 0 (offset 0)
Ignoring wrong pointing object 96 0 (offset 0)
Ignoring wrong pointing object 97 0 (offset 0)
Ignoring wrong pointing object 98 0 (offset 0)
Ignoring wrong pointing object 99 0 (offset 0)
Ignoring wrong pointing object 100 0 (offset 0)
Ignoring wrong pointing object 101 0 (offset 0)
Ignoring wrong pointing object 102 0 (offset 0)
Ignoring wrong pointing object 103 0 (offset 0)
Ignoring wrong pointing object 104 0 (offset 0)
Ignoring wrong pointing object 105 0 (offset 0)
Ignoring wrong pointing object 106 0 (offset 0)
Ignoring wrong pointing object 107 0 (offset 0)
Ignoring wrong pointing object 108 0 (offset 0)
Ignoring wrong pointing object 109 0 (offset 0)
Ignoring wrong pointing object 110 0 (offset 0)
Ignoring wrong pointing object 111 0 (offset 0)
Ignoring wrong pointing object 112 0 (offset 0)
Ignoring wrong pointing object 113 0 (offset 0)
Ignoring wrong pointing object 114 0 (offset 0)
Ignoring wrong pointing object 115 0 (offset 0)
Ignoring wrong pointing object 116 0 (offset 0)
Ignoring wrong pointing object 117 0 (offset 0)
Ignoring wrong pointing object 118 0 (offset 0)
Ignoring wrong pointing object 119 0 (offset 0)
Ignoring wrong pointing object 120 0 (offset 0)
Ignoring wrong pointing object 121 0 (offset 0)
Ignoring wrong pointing object 122 0 (offset 0)
Ignoring wrong pointing object 123 0 (offset 0)
Ignoring wrong pointing object 124 0 (offset 0)
Ignoring wrong pointing object 125 0 (offset 0)
Ignoring wrong pointing object 126 0 (offset 0)
Ignoring wrong pointing object 127 0 (offset 0)
Ignoring wrong pointing object 128 0 (offset 0)
Ignoring wrong pointing object 129 0 (offset 0)
Ignoring wrong pointing object 130 0 (offset 0)
Ignoring wrong pointing object 131 0 (offset 0)
Ignoring wrong pointing object 132 0 (offset 0)
Ignoring wrong pointing object 133 0 (offset 0)
Ignoring wrong pointing object 134 0 (offset 0)
Ignoring wrong pointing object 135 0 (offset 0)
Ignoring wrong pointing object 136 0 (offset 0)
Ignoring wrong pointing object 137 0 (offset 0)
Ignoring wrong pointing object 138 0 (offset 0)
Ignoring wrong pointing object 139 0 (offset 0)
Ignoring wrong pointing object 140 0 (offset 0)
Ignoring wrong pointing object 141 0 (offset 0)
Ignoring wrong pointing object 142 0 (offset 0)
Ignoring wrong pointing object 143 0 (offset 0)
Ignoring wrong pointing object 144 0 (offset 0)
Ignoring wrong pointing object 145 0 (offset 0)
Ignoring wrong pointing object 146 0 (offset 0)
Ignoring wrong pointing object 147 0 (offset 0)
Ignoring wrong pointing object 148 0 (offset 0)
Ignoring wrong pointing object 149 0 (offset 0)
Ignoring wrong pointing object 150 0 (offset 0)
Ignoring wrong pointing object 151 0 (offset 0)
Ignoring wrong pointing object 152 0 (offset 0)
Ignoring wrong pointing object 153 0 (offset 0)
Ignoring wrong pointing object 154 0 (offset 0)
incorrect startxref pointer(3)
parsing for Object Streams
incorrect startxref pointer(3)
incorrect startxref pointer(3)
incorrect startxref pointer(3)
incorrect startxref pointer(3)
incorrect startxref pointer(3)
incorrect startxref pointer(3)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 41 0 (offset 0)
Ignoring wrong pointing object 43 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 170 0 (offset 0)
Ignoring wrong pointing object 203 0 (offset 0)
Ignoring wrong pointing object 519 0 (offset 0)
incorrect startxref pointer(4)
parsing for Object Streams
Object 216 0 not defined.
incorrect startxref pointer(3)
incorrect startxref pointer(3)
incorrect startxref pointer(4)
parsing for Object Streams
Object 66 0 not defined.
EOF marker not found
incorrect startxref pointer(3)
incorrect startxref pointer(3)
incorrect startxref pointer(3)
Ignoring wrong pointing object 255 0 (offset 0)
Ignoring wrong pointing object 257 0 (offset 0)
incorrect startxref pointer(3)
Ignoring wrong pointing object 2 65536 (offset 0)
Ignoring wrong pointing object 44 65536 (offset 0)
Ignoring wrong pointing object 72 65536 (offset 0)
Ignoring wrong pointing object 99 65536 (offset 0)
Ignoring wrong pointing object 125 65536 (offset 0)
Ignoring wrong pointing object 153 65536 (offset 0)
Ignoring wrong pointing object 190 65536 (offset 0)
Ignoring wrong pointing object 218 65536 (offset 0)
Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 26 0 (offset 0)
invalid pdf header: b'\r\n\r\n\r'
incorrect startxref pointer(1)
parsing for Object Streams
incorrect startxref pointer(4)
parsing for Object Streams
Object 179 0 not defined.
incorrect startxref pointer(4)
parsing for Object Streams
Object 209 0 not defined.
incorrect startxref pointer(3)
parsing for Object Streams
invalid pdf header: b'LZ``@'
incorrect startxref pointer(1)
parsing for Object Streams
incorrect startxref pointer(3)
incorrect startxref pointer(4)
parsing for Object Streams
Object 705 0 not defined.
incorrect startxref pointer(3)
incorrect startxref pointer(3)
invalid pdf header: b'\r\n\r\n\r'
CAUTION: startxref found while searching for %%EOF. The file might be truncated and some data might not be read.
EOF marker not found
Ignoring wrong pointing object 2 65536 (offset 0)
Ignoring wrong pointing object 35 65536 (offset 0)
Ignoring wrong pointing object 55 65536 (offset 0)
Ignoring wrong pointing object 74 65536 (offset 0)
Ignoring wrong pointing object 94 65536 (offset 0)
Ignoring wrong pointing object 121 65536 (offset 0)
Ignoring wrong pointing object 140 65536 (offset 0)
incorrect startxref pointer(3)
incorrect startxref pointer(3)
incorrect startxref pointer(4)
parsing for Object Streams
Object 54 0 not defined.
incorrect startxref pointer(3)
incorrect startxref pointer(4)
parsing for Object Streams
Object 298 0 not defined.
incorrect startxref pointer(3)
incorrect startxref pointer(3)
incorrect startxref pointer(3)
parsing for Object Streams
incorrect startxref pointer(3)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 2 65536 (offset 0)
Ignoring wrong pointing object 39 65536 (offset 0)
Ignoring wrong pointing object 77 65536 (offset 0)
Ignoring wrong pointing object 116 65536 (offset 0)
Ignoring wrong pointing object 147 65536 (offset 0)
Ignoring wrong pointing object 178 65536 (offset 0)
Ignoring wrong pointing object 204 65536 (offset 0)
Ignoring wrong pointing object 229 65536 (offset 0)
Ignoring wrong pointing object 266 65536 (offset 0)
Ignoring wrong pointing object 305 65536 (offset 0)
Ignoring wrong pointing object 308 65536 (offset 0)
Ignoring wrong pointing object 342 65536 (offset 0)
Ignoring wrong pointing object 379 65536 (offset 0)
Ignoring wrong pointing object 400 65536 (offset 0)
Ignoring wrong pointing object 403 65536 (offset 0)
Ignoring wrong pointing object 406 65536 (offset 0)
Ignoring wrong pointing object 409 65536 (offset 0)
Ignoring wrong pointing object 412 65536 (offset 0)
Ignoring wrong pointing object 415 65536 (offset 0)
incorrect startxref pointer(3)
incorrect startxref pointer(4)
parsing for Object Streams
Object 1580 0 not defined.
incorrect startxref pointer(3)

Total PDFs  : 1076
Total pages : 13380

                                          filename  size_kb  pages  readable
0     08036c5a50a93da84c5c45ba468c58159d75281e.pdf   391.71      5      True
1     0a29925ccc5e6299e132a73325956a3abef6dd26.pdf    55.83      2      True
2     0e21835a42a6df2405496f62647058ff855743c1.pdf  1194.53      5      True
3     11613a97cef51ad28635fdd86915e74d94cff227.pdf   216.83      5      True
4     12851f0053449570257ff3dfe552621a8dd63d53.pdf   404.51      6      True
...                                            ...      ...    ...       ...
1071  f415cd9cf7bdca0a6a1fde12e0930661927d5b3b.pdf   413.29      5      True
1072  f55a8d69c6047f9037f79225c367766987e25f2b.pdf   206.78      4      True
1073  f997183fa6bf1ef75e31406d98f025c16e527d20.pdf   613.90     49      True
1074  fb8bb0cefab7494ca8c56a4b5b332922e404e465.pdf   358.94      8      True
1075  fb8c6201bfd519374fe7aba9648e678df1b4492d.pdf   396.62      5      True

[1076 rows x 4 columns]

## 4. Indexing Pipeline

In [ ]:
import torch, sys
sys.path.insert(0, 'src')

from loader import load_pdfs
from chunker import chunk_documents
from embedder import Embedder
from vectorstore import VectorStore
from retriever import Retriever

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {DEVICE}')

# Load PDFs
documents = load_pdfs('/kaggle/input/datasets/manisha717/dataset-of-pdf-files/Pdf')

# Chunk
chunks = chunk_documents(documents, chunk_size=500, chunk_overlap=100)

# Embed
embedder = Embedder(device=DEVICE)
embeddings = embedder.encode_chunks(chunks)

# Build FAISS index
vector_store = VectorStore(embedder.embedding_dim)
vector_store.add(embeddings, chunks)
vector_store.save('faiss_index')

# Build retriever
retriever = Retriever(embedder, vector_store)
print('\n✅ Indexing pipeline complete')

Device: cuda
Found 1076 PDF file(s) in '/kaggle/input/datasets/manisha717/dataset-of-pdf-files/Pdf'

Loading PDFs:   1%|          | 12/1076 [00:03<07:05,  2.50it/s]parsing for Object Streams
Loading PDFs:   4%|▍         | 44/1076 [00:53<05:58,  2.88it/s]  incorrect startxref pointer(1)
parsing for Object Streams
Object 47 0 found
Loading PDFs:   5%|▍         | 53/1076 [00:56<04:52,  3.50it/s]parsing for Object Streams
Loading PDFs:   6%|▌         | 62/1076 [01:00<07:05,  2.38it/s]invalid pdf header: b'\r\n\r\n\r'
CAUTION: startxref found while searching for %%EOF. The file might be truncated and some data might not be read.
EOF marker not found

  [WARN] Failed to read '3P5D3UKXU2R6I2TK4OJSLL6LGIQJ4NY5.pdf': Stream has ended unexpectedly

Loading PDFs:   7%|▋         | 76/1076 [01:25<30:24,  1.82s/it]  Ignoring wrong pointing object 1 65536 (offset 0)
Ignoring wrong pointing object 15 65536 (offset 0)
Loading PDFs:   8%|▊         | 88/1076 [01:28<09:23,  1.75it/s]incorrect startxref pointer(3)
Loading PDFs:   9%|▊         | 93/1076 [01:28<04:51,  3.38it/s]

  [WARN] Failed to read '4GJGAIUVBMLM3W7O5SV4EKDNKC4DVOCL.pdf': File has not been decrypted

Loading PDFs:  10%|█         | 111/1076 [01:36<05:59,  2.69it/s]incorrect startxref pointer(3)
Loading PDFs:  11%|█         | 121/1076 [01:38<05:05,  3.13it/s]parsing for Object Streams
Loading PDFs:  12%|█▏        | 129/1076 [01:47<17:13,  1.09s/it]incorrect startxref pointer(3)
Loading PDFs:  13%|█▎        | 139/1076 [01:53<10:27,  1.49it/s]incorrect startxref pointer(4)
parsing for Object Streams
Loading PDFs:  13%|█▎        | 144/1076 [01:54<06:34,  2.36it/s]invalid pdf header: b'\n<!DO'
EOF marker not found

  [WARN] Failed to read '6HTC5FVAQW3DVHYRD7PVJGBBQS7GRZTL.pdf': Stream has ended unexpectedly

Loading PDFs:  17%|█▋        | 182/1076 [02:31<17:58,  1.21s/it]  Ignoring wrong pointing object 2 65536 (offset 0)
Ignoring wrong pointing object 35 65536 (offset 0)
Ignoring wrong pointing object 55 65536 (offset 0)
Ignoring wrong pointing object 74 65536 (offset 0)
Ignoring wrong pointing object 92 65536 (offset 0)
Ignoring wrong pointing object 112 65536 (offset 0)
Ignoring wrong pointing object 139 65536 (offset 0)
Ignoring wrong pointing object 158 65536 (offset 0)
Loading PDFs:  17%|█▋        | 184/1076 [02:32<14:21,  1.03it/s]incorrect startxref pointer(3)
Loading PDFs:  24%|██▍       | 258/1076 [02:55<11:37,  1.17it/s]incorrect startxref pointer(3)
Loading PDFs:  25%|██▌       | 271/1076 [02:57<03:39,  3.67it/s]incorrect startxref pointer(3)
Loading PDFs:  26%|██▋       | 284/1076 [03:04<08:19,  1.59it/s]parsing for Object Streams
Loading PDFs:  27%|██▋       | 286/1076 [03:04<05:44,  2.30it/s]incorrect startxref pointer(3)
incorrect startxref pointer(3)
Loading PDFs:  29%|██▉       | 312/1076 [03:08<01:45,  7.22it/s]EOF marker not found
Loading PDFs:  29%|██▉       | 316/1076 [03:11<04:57,  2.56it/s]

  [WARN] Failed to read 'DEAHZFTA4CQDFDYMRX2NPJCKEHYPIK2Z.pdf': Stream has ended unexpectedly

Loading PDFs:  31%|███       | 334/1076 [03:19<03:56,  3.14it/s]Ignoring wrong pointing object 2 65536 (offset 0)
Ignoring wrong pointing object 44 65536 (offset 0)
Ignoring wrong pointing object 72 65536 (offset 0)
Ignoring wrong pointing object 99 65536 (offset 0)
Ignoring wrong pointing object 125 65536 (offset 0)
Ignoring wrong pointing object 153 65536 (offset 0)
Ignoring wrong pointing object 190 65536 (offset 0)
Ignoring wrong pointing object 218 65536 (offset 0)
Loading PDFs:  32%|███▏      | 349/1076 [03:21<02:17,  5.31it/s]incorrect startxref pointer(3)
Loading PDFs:  33%|███▎      | 353/1076 [03:21<01:24,  8.54it/s]Ignoring padding error: Invalid padding bytes.
Loading PDFs:  35%|███▍      | 376/1076 [03:28<01:48,  6.47it/s]incorrect startxref pointer(3)
XRef object at 1266 can not be read, some object may be missing
Ignoring wrong pointing object 38 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 40 0 (offset 0)
Ignoring wrong pointing object 41 0 (offset 0)
Ignoring wrong pointing object 42 0 (offset 0)
Ignoring wrong pointing object 43 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)
Ignoring wrong pointing object 45 0 (offset 0)
Ignoring wrong pointing object 46 0 (offset 0)
Ignoring wrong pointing object 47 0 (offset 0)
Ignoring wrong pointing object 48 0 (offset 0)
Ignoring wrong pointing object 49 0 (offset 0)
Ignoring wrong pointing object 50 0 (offset 0)
Ignoring wrong pointing object 51 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 53 0 (offset 0)
Ignoring wrong pointing object 54 0 (offset 0)
Ignoring wrong pointing object 55 0 (offset 0)
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 57 0 (offset 0)
Ignoring wrong pointing object 58 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 60 0 (offset 0)
Ignoring wrong pointing object 61 0 (offset 0)
Ignoring wrong pointing object 62 0 (offset 0)
Ignoring wrong pointing object 63 0 (offset 0)
Ignoring wrong pointing object 64 0 (offset 0)
Ignoring wrong pointing object 65 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
Ignoring wrong pointing object 67 0 (offset 0)
Ignoring wrong pointing object 68 0 (offset 0)
Ignoring wrong pointing object 69 0 (offset 0)
Ignoring wrong pointing object 70 0 (offset 0)
Ignoring wrong pointing object 71 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 73 0 (offset 0)
Ignoring wrong pointing object 74 0 (offset 0)
Ignoring wrong pointing object 75 0 (offset 0)
Ignoring wrong pointing object 76 0 (offset 0)
Ignoring wrong pointing object 77 0 (offset 0)
Ignoring wrong pointing object 78 0 (offset 0)
Ignoring wrong pointing object 79 0 (offset 0)
Ignoring wrong pointing object 80 0 (offset 0)
Ignoring wrong pointing object 81 0 (offset 0)
Ignoring wrong pointing object 82 0 (offset 0)
Ignoring wrong pointing object 83 0 (offset 0)
Ignoring wrong pointing object 84 0 (offset 0)
Ignoring wrong pointing object 85 0 (offset 0)
Ignoring wrong pointing object 86 0 (offset 0)
Ignoring wrong pointing object 87 0 (offset 0)
Ignoring wrong pointing object 88 0 (offset 0)
Ignoring wrong pointing object 89 0 (offset 0)
Ignoring wrong pointing object 90 0 (offset 0)
Ignoring wrong pointing object 91 0 (offset 0)
Ignoring wrong pointing object 92 0 (offset 0)
Ignoring wrong pointing object 93 0 (offset 0)
Ignoring wrong pointing object 94 0 (offset 0)
Ignoring wrong pointing object 95 0 (offset 0)
Ignoring wrong pointing object 96 0 (offset 0)
Ignoring wrong pointing object 97 0 (offset 0)
Ignoring wrong pointing object 98 0 (offset 0)
Ignoring wrong pointing object 99 0 (offset 0)
Ignoring wrong pointing object 100 0 (offset 0)
Ignoring wrong pointing object 101 0 (offset 0)
Ignoring wrong pointing object 102 0 (offset 0)
Ignoring wrong pointing object 103 0 (offset 0)
Ignoring wrong pointing object 104 0 (offset 0)
Ignoring wrong pointing object 105 0 (offset 0)
Ignoring wrong pointing object 106 0 (offset 0)
Ignoring wrong pointing object 107 0 (offset 0)
Ignoring wrong pointing object 108 0 (offset 0)
Ignoring wrong pointing object 109 0 (offset 0)
Ignoring wrong pointing object 110 0 (offset 0)
Ignoring wrong pointing object 111 0 (offset 0)
Ignoring wrong pointing object 112 0 (offset 0)
Ignoring wrong pointing object 113 0 (offset 0)
Ignoring wrong pointing object 114 0 (offset 0)
Ignoring wrong pointing object 115 0 (offset 0)
Ignoring wrong pointing object 116 0 (offset 0)
Ignoring wrong pointing object 117 0 (offset 0)
Ignoring wrong pointing object 118 0 (offset 0)
Ignoring wrong pointing object 119 0 (offset 0)
Ignoring wrong pointing object 120 0 (offset 0)
Ignoring wrong pointing object 121 0 (offset 0)
Ignoring wrong pointing object 122 0 (offset 0)
Ignoring wrong pointing object 123 0 (offset 0)
Ignoring wrong pointing object 124 0 (offset 0)
Ignoring wrong pointing object 125 0 (offset 0)
Ignoring wrong pointing object 126 0 (offset 0)
Ignoring wrong pointing object 127 0 (offset 0)
Ignoring wrong pointing object 128 0 (offset 0)
Ignoring wrong pointing object 129 0 (offset 0)
Ignoring wrong pointing object 130 0 (offset 0)
Ignoring wrong pointing object 131 0 (offset 0)
Ignoring wrong pointing object 132 0 (offset 0)
Ignoring wrong pointing object 133 0 (offset 0)
Ignoring wrong pointing object 134 0 (offset 0)
Ignoring wrong pointing object 135 0 (offset 0)
Ignoring wrong pointing object 136 0 (offset 0)
Ignoring wrong pointing object 137 0 (offset 0)
Ignoring wrong pointing object 138 0 (offset 0)
Ignoring wrong pointing object 139 0 (offset 0)
Ignoring wrong pointing object 140 0 (offset 0)
Ignoring wrong pointing object 141 0 (offset 0)
Ignoring wrong pointing object 142 0 (offset 0)
Ignoring wrong pointing object 143 0 (offset 0)
Ignoring wrong pointing object 144 0 (offset 0)
Ignoring wrong pointing object 145 0 (offset 0)
Ignoring wrong pointing object 146 0 (offset 0)
Ignoring wrong pointing object 147 0 (offset 0)
Ignoring wrong pointing object 148 0 (offset 0)
Ignoring wrong pointing object 149 0 (offset 0)
Ignoring wrong pointing object 150 0 (offset 0)
Ignoring wrong pointing object 151 0 (offset 0)
Ignoring wrong pointing object 152 0 (offset 0)
Ignoring wrong pointing object 153 0 (offset 0)
Ignoring wrong pointing object 154 0 (offset 0)
Loading PDFs:  40%|███▉      | 426/1076 [03:59<06:22,  1.70it/s]incorrect startxref pointer(3)
Loading PDFs:  40%|███▉      | 430/1076 [03:59<04:55,  2.19it/s]parsing for Object Streams
Loading PDFs:  40%|████      | 434/1076 [04:00<03:25,  3.13it/s]incorrect startxref pointer(3)
Loading PDFs:  41%|████      | 443/1076 [04:11<14:00,  1.33s/it]incorrect startxref pointer(3)
incorrect startxref pointer(3)
Loading PDFs:  42%|████▏     | 448/1076 [04:12<07:30,  1.40it/s]incorrect startxref pointer(3)
incorrect startxref pointer(3)
Loading PDFs:  42%|████▏     | 452/1076 [04:13<04:53,  2.12it/s]incorrect startxref pointer(3)
Loading PDFs:  43%|████▎     | 458/1076 [04:14<02:38,  3.90it/s]Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 41 0 (offset 0)
Ignoring wrong pointing object 43 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 170 0 (offset 0)
Ignoring wrong pointing object 203 0 (offset 0)
Ignoring wrong pointing object 519 0 (offset 0)
Loading PDFs:  44%|████▍     | 475/1076 [04:27<02:50,  3.52it/s]incorrect startxref pointer(4)
parsing for Object Streams
Object 216 0 not defined.
Loading PDFs:  44%|████▍     | 477/1076 [04:27<02:21,  4.24it/s]

  [WARN] Failed to read 'ILRVVACIV2JDSO4LHLATCOCKSEQYZCMZ.pdf': Invalid object in /Pages

Loading PDFs:  46%|████▌     | 492/1076 [04:33<03:28,  2.81it/s]incorrect startxref pointer(3)
Loading PDFs:  47%|████▋     | 511/1076 [05:07<13:30,  1.43s/it]incorrect startxref pointer(3)
Loading PDFs:  53%|█████▎    | 574/1076 [05:28<04:13,  1.98it/s]incorrect startxref pointer(4)
parsing for Object Streams
Object 66 0 not defined.
Loading PDFs:  53%|█████▎    | 575/1076 [05:28<03:44,  2.23it/s]

  [WARN] Failed to read 'LPA7M5D76YBCPXXCRVU7ZYECI6ODH24E.pdf': 'NoneType' object is not subscriptable

Loading PDFs:  55%|█████▌    | 593/1076 [05:48<04:10,  1.93it/s]EOF marker not found

  [WARN] Failed to read 'MDQ4BAARW6OTVBNBQE7BACYBNCCTWQDO.pdf': Stream has ended unexpectedly

Loading PDFs:  56%|█████▌    | 599/1076 [05:52<05:04,  1.57it/s]incorrect startxref pointer(3)
Loading PDFs:  56%|█████▌    | 602/1076 [05:53<03:59,  1.98it/s]incorrect startxref pointer(3)
Loading PDFs:  58%|█████▊    | 622/1076 [06:01<01:59,  3.79it/s]incorrect startxref pointer(3)
Loading PDFs:  58%|█████▊    | 626/1076 [06:01<01:19,  5.66it/s]Ignoring wrong pointing object 255 0 (offset 0)
Ignoring wrong pointing object 257 0 (offset 0)
Loading PDFs:  59%|█████▉    | 634/1076 [06:04<02:18,  3.20it/s]incorrect startxref pointer(3)
Loading PDFs:  60%|██████    | 646/1076 [06:06<02:03,  3.47it/s]Ignoring wrong pointing object 2 65536 (offset 0)
Ignoring wrong pointing object 44 65536 (offset 0)
Ignoring wrong pointing object 72 65536 (offset 0)
Ignoring wrong pointing object 99 65536 (offset 0)
Ignoring wrong pointing object 125 65536 (offset 0)
Ignoring wrong pointing object 153 65536 (offset 0)
Ignoring wrong pointing object 190 65536 (offset 0)
Ignoring wrong pointing object 218 65536 (offset 0)
Loading PDFs:  60%|██████    | 648/1076 [06:07<02:36,  2.73it/s]Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 26 0 (offset 0)
Loading PDFs:  61%|██████    | 658/1076 [06:11<02:55,  2.39it/s]Multiple definitions in dictionary at byte 0x6e80 for key /im15
Loading PDFs:  62%|██████▏   | 670/1076 [06:12<01:20,  5.07it/s]invalid pdf header: b'\r\n\r\n\r'
incorrect startxref pointer(1)
parsing for Object Streams
Loading PDFs:  64%|██████▍   | 686/1076 [06:14<00:47,  8.16it/s]incorrect startxref pointer(4)
parsing for Object Streams
Object 179 0 not defined.
Loading PDFs:  64%|██████▍   | 689/1076 [06:14<00:35, 10.83it/s]

  [WARN] Failed to read 'P7MWMCFFFSYYNCKYBTUACYK2SLL32AB5.pdf': 'NoneType' object is not subscriptable

Loading PDFs:  66%|██████▋   | 715/1076 [06:19<00:59,  6.03it/s]incorrect startxref pointer(4)
parsing for Object Streams
Object 209 0 not defined.
Loading PDFs:  67%|██████▋   | 719/1076 [06:19<00:45,  7.90it/s]

  [WARN] Failed to read 'QBU5BZSBYX6YRLYVHQU4VCFMBYAHDHLU.pdf': Invalid object in /Pages

incorrect startxref pointer(3)
Loading PDFs:  67%|██████▋   | 722/1076 [06:27<06:10,  1.05s/it]Multiple definitions in dictionary at byte 0x7382 for key /im15
Loading PDFs:  68%|██████▊   | 737/1076 [06:30<02:17,  2.46it/s]parsing for Object Streams
Loading PDFs:  69%|██████▉   | 741/1076 [06:33<02:33,  2.19it/s]invalid pdf header: b'LZ``@'
incorrect startxref pointer(1)
parsing for Object Streams
Loading PDFs:  69%|██████▉   | 745/1076 [06:46<14:21,  2.60s/it]incorrect startxref pointer(3)
Loading PDFs:  70%|██████▉   | 748/1076 [06:46<08:17,  1.52s/it]incorrect startxref pointer(4)
parsing for Object Streams
Object 705 0 not defined.
Loading PDFs:  70%|██████▉   | 752/1076 [06:53<07:49,  1.45s/it]

  [WARN] Failed to read 'R7YJNQZ3EFASORAHOJYEDNW3ZDWBNO4K.pdf': 'NoneType' object is not subscriptable

Loading PDFs:  71%|███████   | 762/1076 [06:55<02:21,  2.23it/s]incorrect startxref pointer(3)
Loading PDFs:  73%|███████▎  | 788/1076 [07:38<17:15,  3.59s/it]incorrect startxref pointer(3)
Loading PDFs:  75%|███████▌  | 810/1076 [07:40<01:39,  2.68it/s]invalid pdf header: b'\r\n\r\n\r'
CAUTION: startxref found while searching for %%EOF. The file might be truncated and some data might not be read.
EOF marker not found

  [WARN] Failed to read 'SW62D5RJMAPDJWHDMA5DLJWWLMSYZE26.pdf': Stream has ended unexpectedly

Loading PDFs:  76%|███████▋  | 822/1076 [07:56<03:53,  1.09it/s]Ignoring wrong pointing object 2 65536 (offset 0)
Ignoring wrong pointing object 35 65536 (offset 0)
Ignoring wrong pointing object 55 65536 (offset 0)
Ignoring wrong pointing object 74 65536 (offset 0)
Ignoring wrong pointing object 94 65536 (offset 0)
Ignoring wrong pointing object 121 65536 (offset 0)
Ignoring wrong pointing object 140 65536 (offset 0)
Loading PDFs:  79%|███████▊  | 845/1076 [08:31<05:27,  1.42s/it]incorrect startxref pointer(3)
Loading PDFs:  84%|████████▍ | 903/1076 [09:02<08:44,  3.03s/it]incorrect startxref pointer(3)
Loading PDFs:  84%|████████▍ | 909/1076 [09:03<03:09,  1.13s/it]incorrect startxref pointer(4)
parsing for Object Streams
Object 54 0 not defined.
Loading PDFs:  85%|████████▍ | 912/1076 [09:03<02:10,  1.25it/s]incorrect startxref pointer(3)

  [WARN] Failed to read 'W432ODS2OFAWYUFA5RQ3B7OWKDQWFXCD.pdf': Invalid object in /Pages

Loading PDFs:  85%|████████▌ | 917/1076 [09:05<01:49,  1.46it/s]incorrect startxref pointer(4)
parsing for Object Streams
Object 298 0 not defined.
Loading PDFs:  85%|████████▌ | 919/1076 [09:05<01:26,  1.82it/s]

  [WARN] Failed to read 'WCILDJ3BDTTDKHJ3HGRQD2SF45E55AXN.pdf': Invalid object in /Pages

Loading PDFs:  86%|████████▌ | 926/1076 [09:10<01:18,  1.92it/s]incorrect startxref pointer(3)
Loading PDFs:  87%|████████▋ | 937/1076 [09:17<01:44,  1.33it/s]incorrect startxref pointer(3)
Loading PDFs:  89%|████████▊ | 953/1076 [09:19<00:21,  5.84it/s]incorrect startxref pointer(3)
parsing for Object Streams
Loading PDFs:  89%|████████▉ | 960/1076 [09:20<00:23,  4.85it/s]incorrect startxref pointer(3)
Loading PDFs:  91%|█████████ | 978/1076 [09:33<02:00,  1.23s/it]Ignoring wrong pointing object 16 0 (offset 0)
Loading PDFs:  92%|█████████▏| 985/1076 [09:37<01:11,  1.28it/s]Ignoring wrong pointing object 2 65536 (offset 0)
Ignoring wrong pointing object 39 65536 (offset 0)
Ignoring wrong pointing object 77 65536 (offset 0)
Ignoring wrong pointing object 116 65536 (offset 0)
Ignoring wrong pointing object 147 65536 (offset 0)
Ignoring wrong pointing object 178 65536 (offset 0)
Ignoring wrong pointing object 204 65536 (offset 0)
Ignoring wrong pointing object 229 65536 (offset 0)
Ignoring wrong pointing object 266 65536 (offset 0)
Ignoring wrong pointing object 305 65536 (offset 0)
Ignoring wrong pointing object 308 65536 (offset 0)
Ignoring wrong pointing object 342 65536 (offset 0)
Ignoring wrong pointing object 379 65536 (offset 0)
Ignoring wrong pointing object 400 65536 (offset 0)
Ignoring wrong pointing object 403 65536 (offset 0)
Ignoring wrong pointing object 406 65536 (offset 0)
Ignoring wrong pointing object 409 65536 (offset 0)
Ignoring wrong pointing object 412 65536 (offset 0)
Ignoring wrong pointing object 415 65536 (offset 0)
Loading PDFs:  92%|█████████▏| 992/1076 [09:45<01:11,  1.17it/s]incorrect startxref pointer(3)
incorrect startxref pointer(4)
parsing for Object Streams
Object 1580 0 not defined.
Loading PDFs:  92%|█████████▏| 995/1076 [09:52<02:06,  1.56s/it]

  [WARN] Failed to read 'YFPURNDOL6TDJBBMD6FIMGPZ64OBYAQ6.pdf': Invalid object in /Pages

Loading PDFs:  93%|█████████▎| 1006/1076 [09:56<00:28,  2.46it/s]incorrect startxref pointer(3)
Loading PDFs: 100%|██████████| 1076/1076 [10:34<00:00,  1.69it/s]

Extracted text from 12099 page(s) across 1076 PDF(s)
Generated 81539 chunk(s) from 12099 page(s) [size=500, overlap=100]
Loading embedding model: sentence-transformers/all-MiniLM-L6-v2

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Embedding dimension: 384

Batches:   0%|          | 0/1275 [00:00<?, ?it/s]

Generated 81539 embeddings of dim 384
VectorStore: 81539 vector(s) indexed
VectorStore saved → faiss_index

✅ Indexing pipeline complete

## 5. Load TinyLlama LLM

In [42]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline as hf_pipeline

LLM_MODEL = 'TinyLlama/TinyLlama-1.1B-Chat-v1.0'
DEVICE    = 'cuda' if torch.cuda.is_available() else 'cpu'

print(f'Loading {LLM_MODEL} on {DEVICE}...')

tokenizer = AutoTokenizer.from_pretrained(LLM_MODEL)
llm = AutoModelForCausalLM.from_pretrained(
    LLM_MODEL,
    dtype=torch.float16 if DEVICE == 'cuda' else torch.float32,
    device_map='auto' if DEVICE == 'cuda' else None,
)
if DEVICE == 'cpu':
    llm = llm.to('cpu')

generator = hf_pipeline(
    'text-generation',
    model=llm,
    tokenizer=tokenizer,
    device=None if DEVICE == 'cuda' else -1,
)
print('✅ LLM loaded')

Loading TinyLlama/TinyLlama-1.1B-Chat-v1.0 on cuda...

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

✅ LLM loaded

## 6. RAG Query Function

In [43]:
FALLBACK = 'I could not find relevant information in the document collection.'

PROMPT_TEMPLATE = """<|system|>
You are a helpful assistant. Answer questions strictly using the provided context.
If the answer is not in the context, say: \"{fallback}\"
</s>
<|user|>
Context:
{context}

Question: {question}
</s>
<|assistant|>
"""

def rag_query(question, top_k=5):
    results  = retriever.retrieve(question, top_k=top_k)
    context  = retriever.format_context(results)
    citations = retriever.format_citations(results)

    prompt = PROMPT_TEMPLATE.format(
        fallback=FALLBACK, context=context, question=question
    )

    output = generator(
        prompt,
        max_new_tokens=512,
        do_sample=False,
        repetition_penalty=1.1,
        pad_token_id=tokenizer.eos_token_id,
    )

    full_text = output[0]['generated_text']
    answer    = full_text[len(prompt):].strip()

    return {
        'question': question,
        'answer':   answer or FALLBACK,
        'sources':  citations,
    }

print('✅ rag_query() ready')

✅ rag_query() ready

## 7. Run a Test Query

In [ ]:
QUESTION = 'What is the main topic discussed in the documents?'

result = rag_query(QUESTION, top_k=5)

print('=' * 60)
print(f'QUESTION: {result["question"]}')
print('=' * 60)
print(f'ANSWER:\n{result["answer"]}')
print()
print('SOURCES:')
for src in result['sources']:
    print(f"  [{src['source_num']}] {src['filename']} — page {src['page_number']} (score={src['score']})")
    print(f"      {src['snippet'][:150]}...")
    print()

Both `max_new_tokens` (=512) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

============================================================
QUESTION: What is the main topic discussed in the documents?
============================================================
ANSWER:
The main topic discussed in the documents is the relevance of documents.

SOURCES:
  [1] LCFQJGJLCOJ56B3YM3XIPRJ7DFUQPTDG.pdf — page 96 (score=0.6223)
      the relevant
documents....

  [2] NKJZFXDHGHWNNHGULXM5PSPE7GWWUTR2.pdf — page 121 (score=0.5676)
      - 115 -







APPENDIX B - MEMORANDUM OF UNDERSTANDING...

  [3] SYBT26QCMSRHEOFZDZM4TZ5CCJ6T34MF.pdf — page 53 (score=0.5491)
      ns the following sections:
Issue: A brief question framing the issue or topic.
Issue Description: A description of the issue or topic plus (if appro...

  [4] 4UCZ4AEHAQQE2MYSFOGR6GRRPKNIAFCW.pdf — page 1 (score=0.5103)
      n 10.)
X
Is the document necessary to protect or safeguard the health, welfare (budget
levels necessary to provide services to the citizens of the sta...

  [5] MMSNF4WV7XLHQFKEQYKHHH7GJPPQJQ7U.pdf — page 33 (score=0.5088)
      LaThuile Italy / David Finley, Fermilab / March 2007            Slide 33
Some Web References for this  talk
• Web site with many of the items in this ...

## 8. Evaluation

In [ ]:
import pandas as pd

EVAL_QUESTIONS = [
    'What is the main topic discussed in the first document?',
    'Summarize the key points of the document collection.',
    'What specific information is provided about any technical topic?',
    'What conclusions or recommendations are made?',
    'Are there any data, statistics, or numbers mentioned?',
]

rows = []
for q in EVAL_QUESTIONS:
    r = rag_query(q, top_k=5)
    top_src = r['sources'][0] if r['sources'] else {}
    rows.append({
        'question':          q,
        'answer_preview':    r['answer'][:200],
        'top_source':        top_src.get('filename', '-'),
        'top_page':          top_src.get('page_number', '-'),
        'top_score':         top_src.get('score', 0),
        'has_fallback':      r['answer'] == 'I could not find relevant information in the document collection.',
    })

df_eval = pd.DataFrame(rows)
display(df_eval)

# Save results
import os                                                                                                                                                
os.makedirs('outputs', exist_ok=True)                                                                                                                    

df_eval.to_markdown('outputs/evaluation_results.md', index=False)                                                                                        
print('\n✅ Evaluation saved → outputs/evaluation_results.md')

Both `max_new_tokens` (=512) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=512) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=512) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=512) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=512) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,question,answer_preview,top_source,top_page,top_score,has_fallback
0,What is the main topic discussed in the first ...,The main topic discussed in the first document...,LCFQJGJLCOJ56B3YM3XIPRJ7DFUQPTDG.pdf,96,0.5228,False
1,Summarize the key points of the document colle...,The given documents are intended for a proposa...,APSZJI6LK7RTS54T7IXF4JHQFEOPNCCZ.pdf,5,0.4681,False
2,What specific information is provided about an...,Sources in your Participant Guide for ideas ab...,DOPBKNWBER76WVPP654XCUJGCQEGSOZY.pdf,69,0.5825,False
3,What conclusions or recommendations are made?,The given context contains three sources:\n\n1...,ZYUTCEHUM7TZDJS75XRY72MWSWNR2QPF.pdf,3,0.5927,False
4,"Are there any data, statistics, or numbers men...","Yes, there are several data, statistics, and n...",GF4OGED6DIFR5WHABHTLSTFV7656GKN3.pdf,2,0.5607,False

✅ Evaluation saved → outputs/evaluation_results.md

## 9. Save Sample Results

In [46]:
import json, datetime

sample_result = rag_query(QUESTION, top_k=5)

md_content = f"""# Sample RAG Results

Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Question
{sample_result['question']}

## Answer
{sample_result['answer']}

## Sources
"""

for src in sample_result['sources']:
    md_content += f"""\n### [{src['source_num']}] {src['filename']} — Page {src['page_number']}
- **Similarity Score:** {src['score']}
- **Snippet:** {src['snippet']}
"""

with open('outputs/sample_results.md', 'w') as f:
    f.write(md_content)

print('✅ Sample results saved → outputs/sample_results.md')
print(md_content[:500])

Both `max_new_tokens` (=512) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

✅ Sample results saved → outputs/sample_results.md
# Sample RAG Results

Generated: 2026-05-31 07:41:26

---

## Question
What is the main topic discussed in the documents?

## Answer
The main topic discussed in the documents is the relevance of documents.

## Sources

### [1] LCFQJGJLCOJ56B3YM3XIPRJ7DFUQPTDG.pdf — Page 96
- **Similarity Score:** 0.6223
- **Snippet:** the relevant
documents.

### [2] NKJZFXDHGHWNNHGULXM5PSPE7GWWUTR2.pdf — Page 121
- **Similarity Score:** 0.5676
- **Snippet:** - 115 -







APPENDIX B - MEMORANDUM OF UND

## 10. Launch Streamlit App via ngrok

In [ ]:
import subprocess                                                                                                                                        
import threading                                                                                                                                         
import time                                                                                                                                              
from pyngrok import ngrok                                                                                                                                

NGROK_TOKEN = 'x'                                                                                      
ngrok.set_auth_token(NGROK_TOKEN)                                                                                                                        

def run_streamlit():                                                                                                                                     
    subprocess.run([                                                                                                                                     
        'streamlit', 'run', 'src/streamlit_app.py',                                                                                                      
        '--server.port', '8501',                                                                                                                         
        '--server.headless', 'true'                                                                                                                      
    ])                                                                                                                                                   

t = threading.Thread(target=run_streamlit, daemon=True)                                                                                                  
t.start()                                                                                                                                                

print("Starting Streamlit...")                                                                                                                           
time.sleep(5)                                                                                                                                            

try:                                                                                                                                                     
    ngrok.kill()                                                                                                                                         
    tunnel = ngrok.connect(8501)                                                                                                                         
    print(f'\n🌐 Streamlit URL Anda berhasil dibuat!')                                                                                                   
    print(f'Buka tautan ini: {tunnel.public_url}')                                                                                                       
except Exception as e:                                                                                                                                   
    print(f'\n❌ Error saat menghubungkan Ngrok: {e}')

Starting Streamlit...

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


🌐 Streamlit URL Anda berhasil dibuat!
Buka tautan ini: https://ranae-puffy-adrenally.ngrok-free.dev